### ISSUE TITLE
Internal error during connect: name 'false' is not defined

### ISSUE THREAD

**Issue by jarrettv** [lhndo/ResHelper#4]
I'm getting the following klipper error:
`Internal error during connect: name 'false' is not defined` after following all the install steps.

If I remove the `[include reshelper.cfg]` from my `printer.cfg` then the error goes away.

**Comment by lhndo** [comment]
Hi,

Can you please enter: RUN_SHELL_COMMAND in the console and tell me the command output?

**Comment by jarrettv** [comment]
looks like I grab the install file:

`https://github.com/dw-0/kiauh/blob/master/scripts/gcode_shell_command.sh`

instead of actual file:

`https://github.com/dw-0/kiauh/blob/master/resources/gcode_shell_command.py`

**Comment by jarrettv** [comment]
Perhaps some better wording for those not using kiauh. Closing.
