### ISSUE TITLE
Error in library(rootSolve) : there is no package called ‘rootSolve’ Execution halted

### ISSUE THREAD

**Issue by mochoandre** [lhndo/ResHelper#5]
Using BTT CB1  I get this error:

`Error in library(rootSolve) : there is no package called ‘rootSolve’ Execution halted`

**Comment by lhndo** [comment]
Thanks for your feedback @aamott. Glad you got it working in the end. 
I have updated the readme with your comment and I hope this will help others!

**Comment by lhndo** [comment]
https://github.com/lhndo/ResHelper/commit/45e60c94cf682830038c885eedd7f1e7038ff5c8
