### ISSUE TITLE
resonance not starting

### ISSUE THREAD

**Issue by bybarbaros** [lhndo/ResHelper#7]
Hello. Thank you for such a macro. I installed the macro without any problems. and when I want to run it I get an error message like this.

08:25
Command {generate_shaper_x} finished
08:25
mv: cannot stat '/home/voron/printer_data/config/RES_DATA/shaper_calibrate_x.png': No such file or directory
08:25
Damping ratio for X calculated:
damping_ratio_x:
08:25
Execution halted
08:25
Error in file(file, "rt") : invalid 'description' argumen

Calls: read.csv -> read.table -> file
08:25
import numpy as np, matplotlib
ModuleNotFoundError: No module named 'numpy'
08:25
Traceback (most recent call last):
File "/home/voron/klipper/scripts/calibrate_shaper.py", line 11, in
08:25
ResHelper: Generating data...
08:25
Running Command {generate_shaper_x}...:
08:25
Unknown command:"TEST_RESONANCES"
08:25
RESONANCE_TEST_X

*******************************************************************
RESHELPER.CFG
**************************************************************
[gcode_shell_command generate_shaper_x]
command: sh /home/voron/ResHelper/gen_x.sh    # If your user is not home/pi, then change this path to match that 
timeout: 60.
verbose: True

[gcode_shell_command generate_shaper_y]
command: sh /home/voron/ResHelper/gen_y.sh    # If your user is not home/pi, then change this path to match that 
timeout: 60.
verbose: True

[gcode_macro RESONANCE_TEST_X]
gcode:
  TEST_RESONANCES axis=x
  RUN_SHELL_COMMAND cmd=generate_shaper_x

[gcode_macro RESONANCE_TEST_Y]
gcode:
  TEST_RESONANCES axis=y
  RUN_SHELL_COMMAND cmd=generate_shaper_y

**Comment by lhndo** [comment]
Hi! It looks like the error comes from the Klipper side when trying to run /home/voron/klipper/scripts/calibrate_shaper.py
and it points out at a missing numpy module. 

Try running the following:
```
pip install -v numpy
sudo apt update
sudo apt install python3-numpy python3-matplotlib libatlas-base-dev
```

**Comment by bybarbaros** [comment]
Thank you.  I will try your advice.

**Comment by lhndo** [comment]
Do you have an adxl accelerometer set up and did you run a successful resonance test as per default klipper manual instructions?

**Comment by bybarbaros** [comment]
I have not done adxl installation and testing before.  I understood properly now.  then first follow thekliper documentation and do a test with adxl 345.  Thank you very much for the help.

**Comment by lhndo** [comment]
> I have not done adxl installation and testing before. I understood properly now. then first follow thekliper documentation and do a test with adxl 345. Thank you very much for the help.

That's correct. These macros only streamline the steps of the process that you would do manually in Klipper. 
First you need to make sure those work as intended. Good luck with the process!

**Comment by bybarbaros** [comment]
Thank you for your good wishes. I performed a manual test by following the input shaping steps in the Clipper documentation you referred to. I wonder how the settings I apply will change the actual part and print in the future. Generally, while the test pieces turn out perfect, I am completely disappointed in the real piece. But thanks to you, I am educating myself better every day. I would like to make a humble suggestion. For me and people like me whose native language is not English and who are new to 3D printers, a small video tutorial in addition to written documents would be great. This is one of the biggest problems I have. It is very difficult to understand and perceive technical issues. And we always learn the subject incompletely. And in the future, when we experience the slightest problem, again on platforms such as github or discord. We create posts for situations that seem very funny to experts. And I really appreciate your time.

**Comment by lhndo** [comment]
Thanks! The video issue has been brought many times in the Klipper community but the issue is that the features are updated so fast that the videos become quickly obsolete in comparison to the official documentation.
The issues during real prints might be due to calibrations and printing profiles. I recommend joining the Voron discord, or your local 3D printing community chats, and asking for help there, describing your issue and posting images.

The Ellis print tuning guide is a great starting point: 
https://ellis3dp.com/Print-Tuning-Guide/
