### ISSUE TITLE
Qidi Printer issue from the beginning

### ISSUE THREAD

**Issue by Hdale85** [lhndo/ResHelper#8]
Hello I'm trying to make this work but running into issues with ./install.sh.

root@mkspi:/home/mks/ResHelper# ./install.sh

ResHelper Installer

printer_data folder not found. Exiting ...

**Comment by lhndo** [comment]
Hello, the issue is that ./install.sh assumes that your config location is in ${HOME}/printer_data/config
You could edit that file and change it.

A simpler is be to copy **reshelper.cfg** into your config folder next to printer.cfg (that's what install.sh does anyways)
Then make sure to include reshelper.cfg into **printer.cfg** and look into reshelper.cfg to make sure your user path is correct.

Let me know if this worked or not

**Comment by Hdale85** [comment]
Ok, I figured it was something to that extent as it looks like all my config files are in klipper_config folder. Let me see if I can make that happen lol.

**Comment by lhndo** [comment]
No worries! 

You need to be in ResHelper folder to run that. do : 
cd ~/ResHelper 
sudo apt install r-base
sudo Rscript install_rs_lib.R

**Comment by Hdale85** [comment]
ok, now I feel dumb lol. I thought I was in that folder.

**Comment by Hdale85** [comment]
Ok....hopefully the last thing lol I really wish this printer used a standard Klipper install! 

root@mkspi:/home/mks/klipper# git update-index --assume-unchanged klippy/extras/gcode_shell_command.py
fatal: Unable to mark file klippy/extras/gcode_shell_command.py

is this a permissions thing?

**Comment by lhndo** [comment]
I've seen that before, you can ignore it for now, it will prob show klipper "dirty" and it's meant to get rid of it.
I couldn't reproduce it on my side but let me test again and I'll reply with a solution if I find why it does it.

**Comment by Hdale85** [comment]
Ok, so it seems to all work fine, but it's trying to put the output images into /home/msk/printer_data/ where do I change that? I did change the user and what not in reshelper.cfg but I don't see anything for output directory in there.

**Comment by lhndo** [comment]
Ah yes, that's correct. I haven't encountered non standard configs so far, sorry. I'll try to harden it in the future.
What's the folder path to your config?

**Comment by Hdale85** [comment]
/home/mks/klipper_config

**Comment by lhndo** [comment]
Ok, that's a bit atypical

Simplest way to do would be to link the folders together while retaining printer_data.
you do it with:

ln -s ${HOME}/printer_data/config/RES_DATA /home/mks/klipper_config/RES_DATA

The other way would be to modify gen_x.sh and gen_y.sh and change the paths in there, but it's a bit much

**Comment by Hdale85** [comment]
So I'd need to make a printer_data folder then, as this machine doesn't have one at all lol.

**Comment by lhndo** [comment]
ok nvm, give a sec to change the scripts and upload them here for you

**Comment by Hdale85** [comment]
Ok sorry! lol. I assume all of the Qidi Q1 Pro's are like this. I'm not sure why they had to change directories and what not.

**Comment by Hdale85** [comment]
Ok thanks I'll give that a try! The klipper folder is still there, and most other things seem normal.

**Comment by lhndo** [comment]
I'll work on an update in the future and add simpler configurable variables for this kind of stuff.
Let me know how it goes!

**Comment by Hdale85** [comment]
Well I thought I had fixed it, it was still trying to move files in and out of the printer_data/config/RES_DATA folder so I made them and used the chmod +x on all of those folders just to make sure permissions were good but it's still giving me some errors. 

Here's the end of what it spit out. 
`13:15:53 
// Traceback (most recent call last):
// File "/home/mks/klipper/scripts/calibrate_shaper.py", line 174, in
// main()
// File "/home/mks/klipper/scripts/calibrate_shaper.py", line 171, in main
// fig.savefig(options.output)
// File "/usr/lib/python3/dist-packages/matplotlib/figure.py", line 2094, in savefig
// self.canvas.print_figure(fname, **kwargs)
// File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 2075, in print_figure
// **kwargs)
// File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py", line 521, in print_png
// cbook.open_file_cm(filename_or_obj, "wb") as fh:
// File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
// return next(self.gen)
// File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 407, in open_file_cm
// fh, opened = to_filehandle(path_or_file, mode, True, encoding)
// File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 392, in to_filehandle
// fh = open(fname, flag, encoding=encoding)
// PermissionError: [Errno 13] Permission denied: '/home/mks/printer_data/config/RES_DATA/shaper_calibrate_x.png'
13:15:54 
// Damping ratio for X calculated:
// damping_ratio_x: 0.015
13:15:54 
// mv: cannot stat '/home/mks/printer_data/config/RES_DATA/shaper_calibrate_x.png': No such file or directory
13:15:54 
// /tmp/resonances_x_20240905_131251.csv
13:15:54 
// Command {generate_shaper_x} finished`

**Comment by lhndo** [comment]
/home/mks/printer_data/config/RES_DATA/shaper_calibrate_x.png << this file shouldn't be generated. are you sure that you replaced the gen_x.sh files? it should generate it in /klipper_config/RES_DATA/

**Comment by Hdale85** [comment]
ok nevermind they didn't get replaced ugh.... I was trying to use SFTP to upload them but apparently I can't copy into that folder. Let me figure this out hold on.

**Comment by Hdale85** [comment]
Heyyyyy it works! lol thanks for all the help! Definitely might wanna put a note somewhere about non standard klipper installs and specifically qidi printers cause everything is there it's just in the wrong directories.

**Comment by lhndo** [comment]
uff, glad to hear you got it! well done!
Yeah, I need to find some time to make it work with non standard installations. It will probably be at the next revision integrating the accel_per_hz branch

regarding  the previous --assume-unchanged error, just ignore it. it's just as a safety measure in case it's needed, and it errors if not

**Comment by Hdale85** [comment]
Ok thanks again, and thanks for your work on the script in general works great.
